AllCops:
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set AFTER THIS LINE
  # in this file are enabled.
  DisabledByDefault: true
  TargetRubyVersion: 2.3
